<?php
/*
		[CrazyWorld]
		A stable Multi-World plugin for PocketMine-MP
		Twitter: @BlockForWhale 
		QQ: 627577391
		Copyright © BlueWhaleNetwork | 2017, Whale
		Please keep author's name and copyright when modifiying.
		Thanks!
		The plugin is updating. Please check my git http://github.com/BlueWhaleNetwork
*/
namespace BlueWhale\CrazyWorld;

class LanguagePack//Language Pack(Do not ask me why I use Class, not Config!!!)
{
	const getLanguage = array(
		"ch" => array(
			"load-world-msg" => "§a正在加载地图 {level}...",
			"del-protect-msg" => "§a[CrazyWorld] 成功取消地图 {level} 的保护！",
			"add-protect-msg" => "§a[CrazyWorld] 成功保护地图 {level}！！",
			"protect-cmd-usage" => "§e[用法] /{cmd} 保护 <地图名称>: §b保护或取消保护一个世界",
			"not-console-admin" => "§c对不起，添加和删除管理员仅限控制台！请到控制台操作",
			"del-admin-msg" => "§a[WMultiWorld] 成功将玩家 {name} 的管理员取消！",
			"add-admin-msg" => "§a[WMultiWorld] 成功将玩家 {name} 设置为多世界管理员！",
			"not-admin-op-msg" => "§c对不起，你不是多世界的独立管理员，请先在控制台添加管理员！%n§b用法： /{cmd} 管理员 <你的ID>",
			"not-admin-player-msg" => "§c对不起，你没有权限使用此指令！",
			"admin-cmd-usage" => "§e[用法] /{cmd} 管理员 <ID>: §b添加或删除一个世界管理员",
			"load-failed-loaded-msg" => "§c[CrazyWorld] 对不起。这个世界{level}已经加载了，无法再次加载",
			"load-failed-msg" => "§c[CrazyWorld] 对不起，地图{level}加载失败！",
			"load-success-msg" => "§a[CrazyWorld] 成功加载地图 {level} !",
			"load-failed-exists-msg" => "§c[CrazyWorld] 对不起，地图 {level} 不存在，无法加载！",
			"load-cmd-usage" => "§e[用法] /{cmd} load <地图名>: §b加载一个地图",
			"unload-failed-not-loaded-msg" => "§c对不起，地图 {level} 未被加载，无法卸载！",
			"unload-failed-msg" => "§c[CrazyWorld] 对不起，地图 {level} 卸载失败！",
			"unload-success-msg" => "§a[CrazyWorld] 成功卸载地图 {level} !",
			"load-cmd-usage" => "§e[用法] /{cmd} unload <地图名>: §b卸载一个已加载的地图",
			"add-banpvp-msg" => "§a[CrazyWorld] 成功设置世界 {level} 为禁止pvp！",
			"del-banpvp-msg" => "§a[CrazyWorld] 成功设置世界 {level} 为允许pvp！",
			"banpvp-cmd-usage" => "§e[用法] /{cmd} banpvp <地图名>: §b添加或删除一个地图到禁止pvp列表",
			"main-help" => "§6=====CrazyWorld=====%n§a/{cmd} 保护: §b设置或取消一个保护世界%n§a/{cmd} banpvp: §b设置或取消一个世界的禁止pvp%n§a/{cmd} admin: §b添加或删除世界管理员(仅限控制台)%n§a/{cmd} load: §b加载一个地图%n§a/{cmd} unload: §b卸载一个地图%n§a/{cmd} oppvp: §b设置是否允许op在禁止pvp的世界pvp%n§a/{cmd} lockgm: §b锁定一个地图的游戏模式%n§a/{cmd} language: §b语言设置%n§a/{cmd} whitelist: §b设置一个地图的白名单%n§a/{cmd} fixname: §b修复所有地图名字%n§a/{cmd} setpos: §b添加或删除一个传送点%n§a/{cmd} delmap: §b删除一个地图存档",
			"allow-op-pvp-msg" => "§a[CrazyWorld] 已允许op在禁止PVP的世界PVP！",
			"disallow-op-pvp-msg" => "§a[CrazyWorld] 已禁止op在禁止PVP的世界PVP！",
			"oppvp-cmd-usage" => "§e[用法] /{cmd} oppvp [true/false]: §b开启或关闭op的PVP",
			"set-gm-survival-msg" => "§a[CrazyWorld] 成功锁定地图{level}的游戏模式为 生存！",
			"set-gm-creative-msg" => "§a[CrazyWorld] 成功锁定地图{level}的游戏模式为 创造！",
			"set-gm-remove-msg" => "§a[CrazyWorld] 成功取消锁定地图{level}的游戏模式！",
			"lockgm-cmd-usage" => "§e====锁定游戏模式====%n§a/{cmd} lockgm <地图名> [0/1]: §b设置地图的游戏模式%n§a/{cmd} lockgm <地图名> remove: §b取消锁定地图的游戏模式",
			"language-cmd-usage" => "§e=====Language=====%n§a/{cmd} language eng: §bEnglish%n§a/{cmd} language ch: §b中文简体%n§a/{cmd} language cho: §b中文繁體",//%n§a/{cmd} language de: §bDeutech%n§a/{cmd} language fr: §bfrançais%n§a/{cmd} language jp: §b日本語%n§a/{cmd} language kr: §b한국어",
			"fixname-success" => "§a[CrazyWorld] 成功修复所有地图的名字！",
			"world-tp-help" => "§6=====CrazyWorld=====%n§a/{cmd} <地图名>: §b传送到目标地图%n§a/{cmd} list: §b查看地图列表",
			"player-use-only-msg" => "对不起，这个指令请到游戏中使用！",
			"no-perm-enter-msg" => "§c对不起，你没有权限进入这个世界！",
			"world-tp-msg" => "§b[CrazyWorld] 你被传送到了世界 {level}",
			"not-exist-world-msg" => "§c[CrazyWorld] 对不起，世界{level}不存在！",
			"makemap-failed-exists-msg" => "§c[CrazyWorld] 对不起，地图{level}已经存在了, 请换个名字！",
			"makemap-making-msg" => "§b[CrazyWorld] 正在生成地图 {level} 中，类型是 {type}，可能会卡顿...",
			"makemap-success-msg" => "§a[CrazyWorld] 成功生成地图！",
			"makemap-deafult-cmd-usage" => "§e[用法] /{cmd} [地图名] default [种子]: §b生成一个原生世界",
			"makemap-failed-unknown-generator-msg" => "§c[CrazyWorld] 生成失败！未知的生成器！",
			"makemap-help" => "§6=====MakeMap=====%n§a/{cmd} [地图名] <生成器>: §b生成一个新地图%n§e>>当前拥有的生成器类型有<<%n§ddefault: §7原生世界%n§dflat: §7超平坦%n§dland: §7领地世界%n§dsnowland: §7雪地领地%n§dwoodflat: §7木头世界",
			"pos-exists-msg" => "§e[CrazyWorld] 名字为{name}的传送点已经存在了，请换个名字或输入/{cmd} setpos <名称> remove 来删除传送点！",
			"remove-pos-success-msg" => "§a[CrazyWorld] 成功删除传送点 {name} !",
			"add-pos-success-msg" => "§a[CrazyWorld] 成功添加传送点 {name} !",
			"set-pos-cmd-usage" => "§e[用法] /{cmd} setpos <名称>: §b设置传送点",
			"protect-msg" => "§c对不起，这个世界被保护了！",
			"banpvp-msg" => "§e=====玩家信息=====%n§aID: {name}%n§b金钱: {money}%n§b饥饿值: {food}%n§b血量: [{hp}/{mhp}]%n§b权限: {isop}",
			"teleport-msg" => "§a你传送到了 {name}",
			"teleport-failed-msg" => "§c传送失败！",
			"pos-not-exist-msg" => "§c对不起，传送点{name}不存在！",
			"tp-cmd-usage" => "§e[用法] /{cmd} <传送点名称>: §b传送到目标传送点",
			"tp-list-msg" => "§6=====传送点列表=====",
			"white-list-msg" => "§c对不起，这个世界禁止进入！",
			"del-whitelist-msg" => "§a[CrazyWorld] 成功将地图 {level} 从白名单删除！",
			"add-whitelist-msg" => "§a[CrazyWorld] 成功将地图 {level} 加入白名单！！",
			"whitelist-cmd-usage" => "§e[用法] /{cmd} whitelist <地图名称>: §b设置一个地图的白名单",
			"delmap-ban-msg" => "对不起，此操作为风险操作，需要配置文件中授权的玩家或控制台才可以使用！请到配置文件修改manager玩家ID，然后再次输入这个指令！",
			"delmap-usage" => "§e[用法] /{cmd} delmap <地图名> yes",
			"delmap-success-msg" => "§a成功删除地图 {world} !",
			"delmap-fail-msg" => "§a删除地图 {world} 失败!",
			"delmap-useless-msg" => "§c删除失败！此地图不存在！"
		),
		"eng" => array(
			"load-world-msg" => "§aLoading world {level}...",
			"del-protect-msg" => "§a[CrazyWorld] Successfully cancelled the protection of {level} !",
			"add-protect-msg" => "§a[CrazyWorld] Successfully set the protection of {level}!!",
			"protect-cmd-usage" => "§e[Usage] /{cmd} protect <world-name>: §bProtect or unprotect a world",
			"not-console-admin" => "§cSorry, this operation need Console!",
			"del-admin-msg" => "§a[WMultiWorld] Successfully cancelled admin {name} !",
			"add-admin-msg" => "§a[WMultiWorld] Successfully set admin {name} !",
			"not-admin-op-msg" => "§cSorry, you have no permission to run this command. Please add admin first!%n§bUsage: /{cmd} admin <ID>",
			/////////////////////////
			"not-admin-player-msg" => "§cSorry, you have no permission to run this command!",
			"admin-cmd-usage" => "§e[Usage] /{cmd} admin <ID>: §badd or delete an admin",
			"load-failed-loaded-msg" => "§c[CrazyWorld] Sorry, world {level} has been loaded.",
			"load-failed-msg" => "§c[CrazyWorld] Loading world {level} failed!",
			/////////////////////////
			"load-success-msg" => "§a[CrazyWorld] Successfully loaded world {level} !",
			"load-failed-exists-msg" => "§c[CrazyWorld] the world {level} can't be loaded due to not exist!",
			"load-cmd-usage" => "§e[Usage] /{cmd} load <world-name>: §bLoad a world",
			"unload-failed-not-loaded-msg" => "§cSorry, world {level} can't be removed due to not loaded!",
			"unload-failed-msg" => "§c[CrazyWorld] Sorry, world {level} removed failed!",
			"unload-success-msg" => "§a[CrazyWorld] Successfully removed world {level} !",
			"load-cmd-usage" => "§e[Usage] /{cmd} unload <world-name>: §bUnload a world",
			"add-banpvp-msg" => "§a[CrazyWorld] Successfully banned pvp in world {level} !",
			"del-banpvp-msg" => "§a[CrazyWorld] Successfully allowed pvp in world {level} !",
			"banpvp-cmd-usage" => "§e[Usage] /{cmd} banpvp <world-name>: §bSet a world pvp permission",
			"main-help" => '§6=====CrazyWorld=====%n§a/{cmd} protect: §bSet protecting world%n§a/{cmd} banpvp: §bSet a world pvp permission%n§a/{cmd} admin: §bAdd or remove a world admin(Only Console use)%n§a/{cmd} load: §bLoad a world%n§a/{cmd} unload: §bUnload a world%n§a/{cmd} oppvp: §bSet if OP can pvp in banned world%n§a/{cmd} lockgm: §bLock gamemode of a world%n§a/{cmd} language: §bSet your language%n§a/{cmd} whitelist: §bSet the whitelist of the worlds%n§a/{cmd} fixname: §bFix all the world name%n§a/{cmd} setpos: §bAdd or remove a teleport point%n§a/{cmd} delmap: §bDelete a world folder',
			"allow-op-pvp-msg" => "§a[CrazyWorld] Successfully allowed op to pvp",
			"disallow-op-pvp-msg" => "§a[CrazyWorld] Successfully banned op to pvp",
			"oppvp-cmd-usage" => "§e[Usage] /{cmd} oppvp [true/false]: §bSet if op can pvp in the banned worlds",
			"set-gm-survival-msg" => "§a[CrazyWorld] Successfully locked gamemode to Survival in world {level} !",
			"set-gm-creative-msg" => "§a[CrazyWorld] Successfully locked gamemode to Creative in world {level} !",
			"set-gm-remove-msg" => "§a[CrazyWorld] Successfully unlocked gamemode in world {level} !",
			"lockgm-cmd-usage" => "§e====GamemodeLocker====%n§a/{cmd} lockgm <world-name> [0/1]: §bLock the world's gamemode%n§a/{cmd} lockgm <world-name> remove: §bUnlock the locking gamemode",
			"language-cmd-usage" => "§e=====Language=====%n§a/{cmd} language eng: §bEnglish%n§a/{cmd} language ch: §b中文简体%n§a/{cmd} language cho: §b中文繁體",//%n§a/{cmd} language de: §bDeutech%n§a/{cmd} language fr: §bfrançais%n§a/{cmd} language jp: §b日本語%n§a/{cmd} language kr: §b한국어",
			"fixname-success" => "§a[CrazyWorld] Successfully fixed all the worlds name!",
			"world-tp-help" => "§6=====CrazyWorld=====%n§a/{cmd} <world-name>: §bTeleport to another world%n§a/{cmd} list: §bSee the world list",
			"player-use-only-msg" => "please use this command in game!",
			"no-perm-enter-msg" => "§cSorry, you have no permission to enter this world!",
			"world-tp-msg" => "§b[CrazyWorld] You have been teleported to world {level}",
			"not-exist-world-msg" => "§c[CrazyWorld] World {level} doesn't exist!",
			"makemap-failed-exists-msg" => "§c[CrazyWorld] Sorry, this name of world has been generated, please change a name!",
			"makemap-making-msg" => "§b[CrazyWorld] Generating world {level}, type {type}, it may take some while..",
			"makemap-success-msg" => "§a[CrazyWorld] Successfully generated a new world!",
			"makemap-deafult-cmd-usage" => "§e[Usage] /{cmd} [world-name] default [seed]: §bGenerate a original world",
			"makemap-failed-unknown-generator-msg" => "§c[CrazyWorld] Failed to generate! Unknown generator!",
			"makemap-help" => "§6=====MakeMap=====%n§a/{cmd} [world-name] <generator-type>: §bMake a new world%n§e>>List of generators<<%n§ddefault: §7Original world%n§dflat: §7Super Flat%n§dland: §7Land world%n§dsnowland: §7Snowland world%n§dwoodflat: §7Wood SuperFlat",
			"pos-exists-msg" => "§e[CrazyWorld] Existing position named {name} , you can delete it by /{cmd} setpos <pos-name> remove",
			"remove-pos-success-msg" => "§a[CrazyWorld] Successfully deleted teleport position {name} !",
			"add-pos-success-msg" => "§a[CrazyWorld] Successfully added teleport position {name} !",
			"set-pos-cmd-usage" => "§e[Usage] /{cmd} setpos <pos-name>: §bSet the teleport position",
			"protect-msg" => "§cSorry, this world has been protected!",
			"banpvp-msg" => "§e=====Player Info=====%n§aID: {name}%n§bMoney: {money}%n§bHunger: {food}%n§bHealth: [{hp}/{mhp}]%n§bPermission: {isop}",
			"teleport-msg" => "§aTeleporting to {name}",
			"teleport-failed-msg" => "§cTeleporting failed!",
			"pos-not-exist-msg" => "§cSorry, transfer point {name} is not exist",
			"tp-cmd-usage" => "§e[Usage] /{cmd} <point-name>: §bTeleport to ...",
			"tp-list-msg" => "§6=====Point List=====",
			"white-list-msg" => "§cSorry, this world are not allowed to enter!",
			"del-whitelist-msg" => "§a[CrazyWorld] Successfully deleted {level} from whitelist world!",
			"add-whitelist-msg" => "§a[CrazyWorld] Successfully added {level} to whitelist world!",
			"whitelist-cmd-usage" => "§e[Usage] /{cmd} whitelist <world-name>: §bSet a world whitelist",
			"delmap-ban-msg" => "Sorry, this command can be only used by Admin or console！Please add Admin first！",
			"delmap-usage" => "§e[Usage] /{cmd} delmap <world-name> yes",
			"delmap-success-msg" => "§aSuccessfully deleted world {world} !",
			"delmap-fail-msg" => "§aFailed to delete world {world} !",
			"delmap-useless-msg" => "§cFailed to delete! World isn't exist!"
		),
		"cho" => array(
			"load-world-msg" => "§a正在加載地圖 {level}...",
			"del-protect-msg" => "§a[CrazyWorld] 成功取消地圖 {level} 的保護！",
			"add-protect-msg" => "§a[CrazyWorld] 成功保護地圖 {level}！！",
			"protect-cmd-usage" => "§e[用法] /{cmd} protect <地圖名稱>: §b保護或取消保護一個世界",
			"not-console-admin" => "§c對不起，添加和刪除管理員僅限在console進行操作！",
			"del-admin-msg" => "§a[WMultiWorld] 成功取消 {name} 的管理員權限",
			"add-admin-msg" => "§a[WMultiWorld] 成功給予 {name} 管理員！",
			"not-admin-op-msg" => "§c對不起，你不是多世界管理員，請先到console添加管理員！%n§b用法： /{cmd} admin <你的ID>",
			"not-admin-player-msg" => "§c對不起，你沒有權限使用此指令！",
			"admin-cmd-usage" => "§e[用法] /{cmd} admin <ID>: §b添加或刪除一個管理員",
			"load-failed-loaded-msg" => "§c[CrazyWorld] 對不起，世界 {level} 已經被加載，無法再次加載",
			"load-failed-msg" => "§c[CrazyWorld] 對不起，地圖{level}加載失敗！",
			"load-success-msg" => "§a[CrazyWorld] 成功加載地圖 {level} !",
			"load-failed-exists-msg" => "§c[CrazyWorld] 對不起，地圖 {level} 不存在，無法加載！",
			"load-cmd-usage" => "§e[用法] /{cmd} load <地圖名字>: §b加載一個地圖",
			"unload-failed-not-loaded-msg" => "§c對不起，地圖 {level} 沒有被加載，無法卸載！",
			"unload-failed-msg" => "§c[CrazyWorld] 對不起，地圖 {level} 卸載失敗！",
			"unload-success-msg" => "§a[CrazyWorld] 成功卸載地圖 {level} !",
			"load-cmd-usage" => "§e[用法] /{cmd} unload <地圖名>: §b卸載一個已經加載過的地圖",
			"add-banpvp-msg" => "§a[CrazyWorld] 成功設置世界 {level} 為禁止pvp！",
			"del-banpvp-msg" => "§a[CrazyWorld] 成功設置世界 {level} 為允許pvp！",
			"banpvp-cmd-usage" => "§e[用法] /{cmd} banpvp <地圖名>: §b添加或刪除一個世界到禁止PVP列表",
			"main-help" => '§6=====CrazyWorld=====%n§a/{cmd} protect: §b設置或取消一個保護世界%n§a/{cmd} banpvp: §b設置或取消一個世界的禁止PVP%n§a/{cmd} admin: §b添加或刪除世界管理員(僅限console)%n§a/{cmd} load: §b加載一個地圖%n§a/{cmd} unload: §b卸載一個地圖%n§a/{cmd} oppvp: §b設置是否允許op進行pvp%n§a/{cmd} lockgm: §b鎖定一個地圖的遊戲模式%n§a/{cmd} language: §b語言設置%n§a/{cmd} whitelist: §b設定一個地圖的白名單%n§a/{cmd} fixname: §b修复地圖名字%n§a/{cmd} setpos: §b设置一个传送点%n§a/{cmd} delmap: §b删除一個地圖档案',
			"allow-op-pvp-msg" => "§a[CrazyWorld] 已允許op在禁止pvp的世界PVP！",
			"disallow-op-pvp-msg" => "§a[CrazyWorld] 已禁止op在禁止PVP的世界PVP！",
			//////////
			"oppvp-cmd-usage" => "§e[用法] /{cmd} oppvp [true/false]: §b開啓或關閉op的PVP",
			"set-gm-survival-msg" => "§a[CrazyWorld] 成功鎖定地圖{level}的遊戲模式為 生存！",
			"set-gm-creative-msg" => "§a[CrazyWorld] 成功鎖定地圖{level}的遊戲模式為 創造！",
			"set-gm-remove-msg" => "§a[CrazyWorld] 成功取消鎖定地圖{level}的遊戲模式！",
			"lockgm-cmd-usage" => "§e====鎖定遊戲模式====%n§a/{cmd} lockgm <地圖名字> [0/1]: §b設置地圖的遊戲模式%n§a/{cmd} lockgm <地圖名> remove: §b取消鎖定地圖的遊戲模式",
			"language-cmd-usage" => "§e=====Language=====%n§a/{cmd} language eng: §bEnglish%n§a/{cmd} language ch: §b中文简体%n§a/{cmd} language cho: §b中文繁體",//%n§a/{cmd} language de: §bDeutech%n§a/{cmd} language fr: §bfrançais%n§a/{cmd} language jp: §b日本語%n§a/{cmd} language kr: §b한국어",
			"fixname-success" => "§a[CrazyWorld] 成功修復所有地圖的名字！",
			"world-tp-help" => "§6=====CrazyWorld=====%n§a/{cmd} <地圖名字>: §b傳送到目標地圖%n§a/{cmd} list: §b查看地圖列表",
			"player-use-only-msg" => "請到遊戲中使用這個指令！",
			"no-perm-enter-msg" => "§c對不起，你沒有權限進入這個世界！",
			"world-tp-msg" => "§b[CrazyWorld] 你被傳送到了世界 {level}",
			"not-exist-world-msg" => "§c[CrazyWorld] 對不起，世界{level}不存在！",
			"makemap-failed-exists-msg" => "§c[CrazyWorld] 對不起，地圖{level}已經存在了, 請換個名字~",
			"makemap-making-msg" => "§b[CrazyWorld] 正在生成地圖 {level} 中，類型是 {type}，可能會卡頓...",
			"makemap-success-msg" => "§a[CrazyWorld] 成功生成地圖！",
			"makemap-deafult-cmd-usage" => "§e[用法] /{cmd} [地圖名] default [種子]: §b生成一個原生世界",
			"makemap-failed-unknown-generator-msg" => "§c[CrazyWorld] 生成失敗！未知的生成器！",
			"makemap-help" => "§6=====MakeMap=====%n§a/{cmd} [地圖名] <生成器>: §b生成一個新地圖%n§e>>當前擁有的生成器類型有<<%n§ddefault: §7原生世界%n§dflat: §7超平坦%n§dland: §7領地世界%n§dsnowland: §7雪地領地%n§dwoodflat: §7木頭世界",
			"pos-exists-msg" => "§e[CrazyWorld] 名字为{name}的傳送点已经存在了，請换個名字或者键入/{cmd} setpos <名稱> remove 来删除传送点！",
			"remove-pos-success-msg" => "§a[CrazyWorld] 成功删除傳送點 {name} !",
			"add-pos-success-msg" => "§a[CrazyWorld] 成功添加傳送點 {name} !",
			"set-pos-cmd-usage" => "§e[用法] /{cmd} setpos <名稱>: §b設定傳送點",
			"protect-msg" => "§c對不起，這個世界被保護了!",
			"banpvp-msg" => "§e=====玩家資訊=====%n§aID: {name}%n§b金錢: {money}%n§b饑餓值: {food}%n§b血量: [{hp}/{mhp}]%n§b許可權: {isop}",
			"teleport-msg" => "§a你傳送到了 {name}",
			"teleport-failed-msg" => "§c傳送失敗！",
			"pos-not-exist-msg" => "§c對不起，傳送點{name}不存在！",
			"tp-cmd-usage" => "§e[用法] /{cmd} <傳送點名稱>：§b傳送到目標傳送點",
			"tp-list-msg" => "§6=====傳送點清單=====",
			"white-list-msg" => "§c對不起，這個世界禁止進入!",
			"del-whitelist-msg" => "§a[CrazyWorld]成功將地圖{level}從白名單删除！",
			"add-whitelist-msg" => "§a[CrazyWorld]成功將地圖{level}加入白名單！！",
			"whitelist-cmd-usage" => "§e[用法] /{cmd} whitelist <地圖名稱>：§b設定一個地圖的白名單",
			"delmap-ban-msg" => "對不起，此操作为风险操作，需要配置文件中授权的玩家或控制台才可以使用！请到配置文件修改manager玩家ID，然后再次输入这个指令！",
			"delmap-usage" => "§e[用法] /{cmd} delmap <地圖名稱> yes",
			"delmap-success-msg" => "§a成功删除地图 {world} !",
			"delmap-fail-msg" => "§a删除地图 {world} 失败!",
			"delmap-useless-msg" => "§c删除失败！此地图不存在！"
		)
	);
}